### ISSUE TITLE
在1.19.2版本中，点击接受传送功能失效，原因好像是命令从tpAccept变成了tpaccept

### ISSUE THREAD

**Issue by fyachan** [carm-outsource/MoeTeleport#11]
**问题简述**

在Arclight 1.19版本中，点击接受传送功能失效，但手动使用/tpaccept可以接受，猜测是命令从tpAccept变成了tpaccept导致

**问题来源**

**预期结果**(可选)

**问题截图/问题报错**

![屏幕截图(2)](https://user-images.githubusercontent.com/92874250/212593950-12c15864-486b-44bf-8106-4e9c1de15f75.png)

![Snipaste_2023-01-16_11-35-26](https://user-images.githubusercontent.com/92874250/212593436-545bfbd0-a043-4bd7-8b0c-bfe961497e43.jpg)
**操作环境**

> version
[03:32:25 INFO] [Console]: This server is running Arclight version arclight-1.19.2-1.0.1-0550c6cd (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT)

**其他补充**

**Comment by CarmJos** [comment]
您好，这个问题应该不是插件的问题。建议您尝试将配置文件中点击执行的对应指令修改为 `/MoeTeleport:tpAccept` 再试一次。

**Comment by fyachan** [comment]
感谢回答，我把messages.yml中的 run_command=/tpAccept 改为 run_command=/tpaccept 后就可以正常使用了。
原因我搜索了一下发现，好像是从1.19.1版本开始，命令都变为小写的了，[https://www.spigotmc.org/threads/commands-case-sensitive-after-1-19-1-update.566912](https://www.spigotmc.org/threads/commands-case-sensitive-after-1-19-1-update.566912)这个帖子中也有提到。

**Comment by CarmJos** [comment]
很高兴问题已解决！

如果您乐于参与项目的贡献，您可以修改本项目中的[源代码](https://github.com/carm-outsource/MoeTeleport/blob/master/src/main/java/cc/carm/plugin/moeteleport/configuration/PluginMessages.java)，将消息中全部的指令变更为 `/moeteleport:xxx` 的格式，并提交PR。您将被添加至项目的贡献者列表，并为后续所有的使用者解决该问题。

若您没有足够的时间这么做，您可以直接关闭本Issues，我稍后会自行修复该问题。

**Comment by CarmJos** [comment]
您好，三天后我将关闭本Issues，并选择自行修复此问题。
