### ISSUE TITLE
添加传送冷却

### ISSUE THREAD

**Issue by TalentsDX** [carm-outsource/MoeTeleport#8]
**功能简述**
  为所有传送功能添加一个冷却时间

**需求来源**
  玩家可以无任何冷却的传送来传送去，导致可以利用这个机制，在打怪时残血了，可以回家补血然后继续back回去打

**Comment by CarmJos** [comment]
感谢反馈！ 该功能将在下个版本中支持。

**Comment by CarmJos** [comment]
该功能将随 [4.0.0]() 版本发版后支持，欢迎您下载测试使用。
