### ISSUE TITLE
不能在Mohist上正常运行

### ISSUE THREAD

**Issue by Zhou-Shilin** [carm-outsource/MoeTeleport#9]
**问题简述**
不能在Mohist核心上正常运行
输入指令时报错：An internal error occurred while attempting to perform this command

**问题来源**

1. 使用Mohist核心开服，并安装本插件
2. 玩家输入'/sethome'或其他指令
3. 出现了报错 'An internal error occurred while attempting to perform this command'

**问题截图/问题报错**
An internal error occurred while attempting to perform this command

**操作环境**
This server is running Mohist version 1.18.2 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT, Forge version 40.1.68)

**其他补充**
无

**Comment by CarmJos** [comment]
您好，您提供的报错信息不全面，我无法为您提供任何帮助。

**Comment by CarmJos** [comment]
暂无下文，本议题结束。如有需要可以重新提交新议题。
